name: Selenium Pytest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      # We use 'xvfb-run' to provide a virtual display for the browser
      run: |
        pytest tests/pytest_end_to_end.py --junitxml=report.xml

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.xml